spring:
  application:
    name: kark-profit
  jackson:
    property-naming-strategy: SNAKE_CASE
  cache:
    type: caffeine

#  profiles:
#    active: local

  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    hibernate:
      ddl-auto: none   # auto create/update tables
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /kark-profit

app:
  cors:
    allowed-origins: https://byte-income.onrender.com
    allowed-methods: GET,POST

telegram:
  bot:
    token: ${telegram.bot.token:123}
    chat-id: ${telegram.bot.chat-id:123}