spring:
  application:
    name: kark-profit
  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: Asia/Phnom_Penh
  cache:
    type: caffeine

  profiles:
    active: local

  transaction:
    default-timeout=30:
    rollback-on-commit-failure: true
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    hibernate:
      ddl-auto: none   # auto create/update tables
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /kark-profit
